name: crs_undergrad
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_ui_firestore: ^1.6.1
  flutter:
    sdk: flutter
  form_validator: ^2.1.1
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/mainscreen_bg.png
    - assets/images/plm_logo.png
